### ISSUE TITLE
KeyError: 'geo'

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Rhein-Neckar/ffrn-expansion-map#16]
I cannot generate the list for our community in kiel:

```
python3 ./mkpoly -f ffmap http://mesh.freifunk.in-kiel.de/data/nodes.json
Traceback (most recent call last):
  File "./mkpoly", line 178, in <module>
    main(args.url, args.format)
  File "./mkpoly", line 116, in main
    nodes = fetch(url, fmt)
  File "./mkpoly", line 42, in fetch
    for node in document['nodes']
  File "./mkpoly", line 43, in <dictcomp>
    if node['geo']}
KeyError: 'geo'
```

**Comment by rubo77** [comment]
With our old map data it works a bit better:

    ./mkpoly -f ffmap http://graph.freifunk.in-kiel.de/json/nodes.json

this takes about 30seconds and then I get the error:

```
Could not find a municipal area for the location!
Traceback (most recent call last):
  File "./mkpoly", line 178, in <module>
    main(args.url, args.format)
  File "./mkpoly", line 128, in main
    raise KeyError("No valid areas found.")
KeyError: 'No valid areas found.'
```
