### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Rhein-Neckar/ffrn-expansion-map#17]
Your example in the README doesn't work any more, the URL is 404.

When I look for the new nodes.json, I get:

```
./mkpoly -f ffmap https://map.ffrn.de/data/nodes.json
Traceback (most recent call last):
  File "./mkpoly", line 178, in <module>
    main(args.url, args.format)
  File "./mkpoly", line 116, in main
    nodes = fetch(url, fmt)
  File "./mkpoly", line 42, in fetch
    for node in document['nodes']
  File "./mkpoly", line 43, in <dictcomp>
    if node['geo']}
TypeError: string indices must be integers
```

**Comment by nazco** [comment]
kein bug, war nur alte doku
