### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by sap-dev** [Freifunk-Rhein-Neckar/ffrn-expansion-map#8]
Hallo,

diesen Fehler bekomme ich bei unserem Script. Woran kann das liegen?

/var/www/ffrn-expansion-map# ./mkpoly -f nodelist http://gw01.osnabrueck.freifunk.net/data/nodelist.json
Traceback (most recent call last):
  File "./mkpoly", line 171, in <module>
    main(args.url, args.format)
  File "./mkpoly", line 118, in main
    local = get_municipal_area(areas)
  File "./mkpoly", line 104, in get_municipal_area
    return max(filter(is_municipal, areas.items()), key=get_type)[1]
ValueError: max() arg is an empty sequence

**Comment by nazco** [comment]
Ich vermute das unsere Parser nicht auf eure Version des Meshviewers passt und ihr daher eine leere Liste an Koordinaten bekommt. Damit kann natürlich nicht weiter gearbeitet werden.

**Comment by sap-dev** [comment]
Könnte man unsere json entsprechend bearbeiten?

**Comment by mweinelt** [comment]
Die nodelist.json ist standardisiert und daher unproblematisch.

`ValueError: max() arg is an empty sequence` besagt, dass das Ergebnis des filters leer ist.

@sap-dev Kannst du das nochmal gegen den aktuellen HEAD probieren?
